vich_uploader:
    db_driver: orm

    mappings:
        member_attachments:
            uri_prefix: "%app.path.member_attachments%"
            upload_destination: '%kernel.project_dir%/public%app.path.member_attachments%'
        event_attachments:
            uri_prefix: "%app.path.event_attachments%"
            upload_destination: '%kernel.project_dir%/public%app.path.event_attachments%'
