vich_uploader:
    db_driver: orm

    mappings:
        team_attachments:
            uri_prefix: "%app.path.team_attachments%"
            upload_destination: '%kernel.project_dir%/public%app.path.team_attachments%'

        event_attachments:
            uri_prefix: "%app.path.event_attachments%"
            upload_destination: '%kernel.project_dir%/public%app.path.event_attachments%'
